name: Hello #ワークフロー名
on: push # イベント（プッシュ時に起動）
jobs: #ジョブの定義
  hello: # ジョブID（ジョブは複数定義できるのでジョブIDで管理する）
    runs-on: ubuntu-latest # ランナー（Ubuntuで実行）
    steps: # ステップの定義
      - run: echo "Hello, world!" # コマンドの実行
      - uses: actions/checkout@v4 # アクションの呼び出し